CREATE DATABASE BookStoreDB

CREATE TABLE BookTable(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
[Name] NVARCHAR(10),
PublisherID INt NOT NULL FOREIGN KEY(PublisherID) REFERENCES PublisherTabl(Id)
AuthorID INT  NOT NULL FOREIGN KEY(AuthorId) REFERENCES AuthorsTable(Id)
GenreID INT NOT NULL FOREIGN KEY(GenreID) REFERENCES GenreTable(Id)
[Page] INT,
[Year] DATETIME
)

CREATE TABLE AuthorsTable(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
[Name] NVARCHAR(15)
)

CREATE TABLE GenreTable(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
Genre NVARCHAR(15)
)

CREATE TABLE Comment(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
ClientID INT FOREIGN KEY(ClientID) REFERENCES ClientTable(Id)
[Text] NVARCHAR(100)
)

CREATE TABLE ClientTable(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
FirstName NVARCHAR(10)
)

CREATE TABLE Publisher(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
FirstName NVARCHAR(10)
)

CREATE TABLE OrdersTable(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY(Id),
ClientID INT NOT NuLL FOREIGN KEY(ClientID) REFERENCES ClientTable(Id),
BookID INT NOT NULL FOREIGN KEY(BookID) REFERENCES BookTable(Id)
)

CREATE TABLE StockTable(
BookID INT NOT NULL FOREIGN KEY(BookID) REFERENCES BookTable(Id),
Quantity INT NOT NULL
)